# image: milesmcc/postback:latest
# note that this image is not (currently) automatically deployed
# you can deploy it with: `fly deploy --config deployments/fly.backups.toml --image milesmcc/postback:latest`
# it will require the following secrets:
#     AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY
#     S3_BUCKET
#     PG_URL
#     AGE_RECIPIENTS
# for more info, see: https://github.com/milesmcc/postback

app = "atlos-backup-generator"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  STORAGE_BACKEND = "S3"
  CRON_SCHEDULE = "20 0,6,12,18 * * *"
  DEFAULT_REGION = "eu-central-1"
  SSL_SECURE = "True"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
