app = "atlos-platform-main"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "platform.atlos.org"
  PORT = "8080"
  S3_BUCKET = "atlos-content-main"
  AWS_REGION = "us-east-1"
  APPSIGNAL_APP_ENV = "prod-main"
  ENVIRONMENT = "prod-main"
  ENABLE_CAPTCHAS = "true"
  RULES_LINK = "https://github.com/milesmcc/atlos/blob/main/policy/RULES.md"
  ATTRIBUTE_OPTIONS = """
    {
      "type": [
        "Military Activity",
        "Military Activity/Movement",
        "Military Activity/Equipment",
        "Military Activity/Equipment/Lost",
        "Military Activity/Execution",
        "Military Activity/Combat",
        "Military Activity/Encampment",
        "Military Activity/Strike",
        "Military Activity/Explosion",
        "Military Activity/Detention",
        "Military Activity/Mass Grave",
        "Civilian Activity",
        "Civilian Activity/Protest or March",
        "Civilian Activity/Riot",
        "Civilian Activity/Violence",
        "Policing",
        "Policing/Use of Force",
        "Policing/Detention",
        "Weather",
        "Weather/Flooding",
        "Weather/Hurricane",
        "Weather/Fire",
        "Other"
      ],
      "impact": [
        "Structure",
        "Structure/Residential",
        "Structure/Residential/House",
        "Structure/Residential/Apartment",
        "Structure/Healthcare",
        "Structure/Humanitarian",
        "Structure/Food Infrastructure",
        "Structure/School or Childcare",
        "Structure/Park or Playground",
        "Structure/Cultural",
        "Structure/Religious",
        "Structure/Industrial",
        "Structure/Administrative",
        "Structure/Commercial",
        "Structure/Roads, Highways, or Transport",
        "Structure/Transit Station",
        "Structure/Airport",
        "Structure/Military",
        "Land Vehicle",
        "Land Vehicle/Car",
        "Land Vehicle/Truck",
        "Land Vehicle/Armored",
        "Land Vehicle/Train",
        "Land Vehicle/Bus",
        "Aircraft",
        "Aircraft/Fighter",
        "Aircraft/Bomber",
        "Aircraft/Helicopter",
        "Aircraft/Drone",
        "Sea Vehicle",
        "Sea Vehicle/Boat",
        "Sea Vehicle/Warship",
        "Sea Vehicle/Aircraft Carrier",
        "Injury",
        "Injury/Civilian",
        "Injury/Soldier",
        "Death",
        "Death/Civilian",
        "Death/Soldier"
      ],
      "equipment": [
        "Small Arm",
        "Munition",
        "Munition/Cluster",
        "Munition/Chemical",
        "Munition/Thermobaric",
        "Munition/Incendiary",
        "Non-Lethal Weapon",
        "Non-Lethal Weapon/Tear Gas",
        "Non-Lethal Weapon/Rubber Bullet",
        "Land Mine",
        "Launch System",
        "Launch System/Artillery",
        "Launch System/Self-Propelled",
        "Launch System/Multiple Launch Rocket System",
        "Land Vehicle",
        "Land Vehicle/Car",
        "Land Vehicle/Armored",
        "Aircraft",
        "Aircraft/Fighter",
        "Aircraft/Bomber",
        "Aircraft/Helicopter",
        "Aircraft/Drone",
        "Sea Vehicle",
        "Sea Vehicle/Small Boat",
        "Sea Vehicle/Ship",
        "Sea Vehicle/Aircraft Carrier"
      ]
    }
  """

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
