[tool.poetry]
name = "utils"
version = "0.1.0"
description = ""
authors = ["R. Miles McCain <github@sendmiles.email>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
unicodecsv = "^0.14.1"
python-dateutil = "^2.8.2"
perception = "^0.6.8"
loguru = "^0.7.0"
warcio = "^1.7.4"
auto-archiver = "^0.5.5"
opencv-python = "^4.7.0.72"
numpy = "^1.24.2"
selenium = "^4.9.0"
webdriver-manager = "^3.8.6"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
