name: Fly Deploy Staging (Fly.io)
on:
  registry_package:
jobs:
  deploy:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name == 'main' }}
    environment:
      name: "Staging (Fly.io)"
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./platform
    concurrency:
      group: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config deployments/fly.staging.toml --image ghcr.io/atlosdotorg/atlos@${{ github.event.registry_package.package_version.container_metadata.tag.digest }} --wait-timeout 300
