# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy staging (Azure)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://atlos.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_1cc713570a104b1e88e405747311fd05 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_9ef858e77b73419ab732d02b1fda0594 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: atlos.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cc713570a104b1e88e405747311fd05 }}/platform:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production" # note: this is still our "staging" instance; production is in an entirely separate resource group
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "atlos-staging"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_70900efc9a264859be1047d3a8237702 }}
          images: "atlos.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cc713570a104b1e88e405747311fd05 }}/platform:${{ github.sha }}"
