name: Keep prod up to date with main
on:
  push:
    branches:
      - main
jobs:
  updateProd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: prod
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          title: "Deploy recent changes to prod"
